_n_gpu:
    value: 1
_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
            "3":
                - 1
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.9.21
            "5": 0.19.9
            "6": 4.21.1
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
auto_find_batch_size:
    value: false
bf16:
    value: false
bf16_full_eval:
    value: false
data_seed:
    value: None
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_pin_memory:
    value: true
ddp_bucket_cap_mb:
    value: None
ddp_find_unused_parameters:
    value: false
debug:
    value: '[]'
deepspeed:
    value: None
disable_tqdm:
    value: false
do_eval:
    value: false
do_predict:
    value: false
do_train:
    value: false
eval_accumulation_steps:
    value: None
eval_batch_size:
    value: 8
eval_delay:
    value: 0
eval_steps:
    value: None
evaluation_strategy:
    value: "no"
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: '[]'
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: None
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
greater_is_better:
    value: None
group_by_length:
    value: false
half_precision_backend:
    value: cuda_amp
hidden_size:
    value: 640
hub_model_id:
    value: None
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: None
label_smoothing_factor:
    value: 0
learning_rate:
    value: 5e-05
length_column_name:
    value: length
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: -1
log_level_replica:
    value: -1
log_on_each_node:
    value: true
logging_dir:
    value: ./v1-esm2-spider-silk-finetuned/runs/Apr17_18-16-36_dgx-1
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_steps:
    value: -1
metric_for_best_model:
    value: None
mp_parameters:
    value: ""
no_cuda:
    value: false
num_hidden_layers:
    value: 30
num_train_epochs:
    value: 3
optim:
    value: adamw_hf
output_dir:
    value: ./v1-esm2-spider-silk-finetuned
overwrite_output_dir:
    value: true
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 8
per_gpu_eval_batch_size:
    value: None
per_gpu_train_batch_size:
    value: None
prediction_loss_only:
    value: false
push_to_hub:
    value: false
push_to_hub_model_id:
    value: None
push_to_hub_organization:
    value: None
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_unused_columns:
    value: true
report_to:
    value: '[''wandb'']'
resume_from_checkpoint:
    value: None
run_name:
    value: v1-ESM2_FineTune_SpiderSilk
save_on_each_node:
    value: false
save_steps:
    value: 100
save_strategy:
    value: steps
save_total_limit:
    value: 4
seed:
    value: 42
sharded_ddp:
    value: '[]'
skip_memory_metrics:
    value: true
tf32:
    value: None
torchdynamo:
    value: None
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: None
train_batch_size:
    value: 8
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
warmup_ratio:
    value: 0
warmup_steps:
    value: 0
weight_decay:
    value: 0.01
xpu_backend:
    value: None
